create table Usr(
  userID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  firstName VARCHAR(30),
  lastName	VARCHAR (30),
  email VARCHAR(30),
  password VARCHAR(30) NOT NULL,
  birthday	DATE,
  gender	VARCHAR(30),
  isAdmin	NUMBER(1)
);

create table Results(
  resultsID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  score NUMBER(10),
  hard NUMBER(1),
  time	DATE,
  topic VARCHAR(30),
  userID	NUMBER(10),
  FOREIGN KEY(userID) REFERENCES Usr(userID)
);
  
create table Challanges(
 challangeID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 hard NUMBER(1),
 time	DATE,
 topic VARCHAR(30),
 challanger	NUMBER(10),
 challanged	NUMBER(10),
 FOREIGN KEY(challanger) REFERENCES Usr(userID),
 FOREIGN KEY(challanged) REFERENCES Usr(userID)
);
  
create table Questions(
  questionID NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  hard NUMBER(1),
  topic	VARCHAR(30),
  correct	VARCHAR(50),
  wrong1	VARCHAR(50),
  wrong2	VARCHAR(50),
  wrong3	VARCHAR(50),
  question VARCHAR(150)
);
  
create table Friends(
  user1 NUMBER(10) PRIMARY KEY NOT NULL,
  user2 NUMBER(10),
  since	DATE,
  status	VARCHAR(30),
  FOREIGN KEY(user1) REFERENCES Usr(userID),
  FOREIGN KEY(user2) REFERENCES Usr(userID)
);

create table Has(
  challangeID NUMBER(10) PRIMARY KEY NOT NULL,
  questionID NUMBER(10),
  FOREIGN KEY(challangeID) REFERENCES Challanges(challangeID),
  FOREIGN KEY(questionID) REFERENCES Questions(questionID)
);

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';

INSERT into Usr values(NULL, 'Admin', 'Admin', 'admin123@gmail.com', 'password123', '1998-03-15', 'male', 1);
INSERT into Usr values(NULL, 'Teszt', 'Elek', 'tesztelek@gmail.com', 'password123', '1998-03-15', 'male', 0);
INSERT into Usr values(NULL, 'Teszt', 'Balázs', 'teszbalazs@gmail.com', 'password123', '1994-06-10', 'male', 0);

INSERT into Results values(NULL, 5, 0, '2019-02-20', 'History', 1);
INSERT into Results values(NULL, 8, 0, '2019-02-24', 'History', 2);

INSERT into Challanges values(NULL, 0, '2019-02-20', 'History', 1, 2);

INSERT INTO Questions VALUES (NULL, 0, 'history', 'Yuri Gagarin', 'Neil Armstrong', 'Jim Lovell', 'Alan Shepard', 'Who was the first man to go to space?');
INSERT INTO Questions VALUES (NULL, 0, 'history', 'George Washington', 'Abraham Lincoln', 'John Adams', 'Thomas Jefferson', 'Who was the first president of the USA?');
INSERT INTO Questions VALUES (NULL, 0, 'history', 'France', 'The UK', 'Spain', 'Switzerland', 'The Statue of Liberty was a gift from which country?');
INSERT INTO Questions VALUES (NULL, 0, 'history', '1939', '1940', '1938', '1941', 'When did WWII start?');
INSERT INTO Questions VALUES (NULL, 0, 'history', '1914', '1910', '1939', '1915', 'During which year did World War I begin?');

INSERT into Friends values(1, 2, '2019-02-19', 'active');

INSERT into Has values(1, 1);
